export const locationIds = [ // Full list of ~50 on section 9.2
  {name: "William J. Clinton Library", id: 1},
  {name: "Dwight D. Eisenhower Library", id: 2},
  {name: "Franklin D. Roosevelt Library", id: 3},
  {name: "George Bush Library", id: 4},
  {name: "Gerald R. Ford Library", id: 5},
  {name: "Gerald R. Ford Museum", id: 6},
  {name: "Herbert Hoover Library", id: 7},
  {name: "Harry S. Truman Library", id: 8},
  {name: "Jimmy Carter Library", id: 9},
  {name: "John F. Kennedy Library", id: 10},
  {name: "Lyndon Baines Johnson", id: 11},
  {name: "Richard Nixon Library - College Park", id: 12},
  {name: "Ronald Reagan Library", id: 13},
  {name: "National Archives at Boston", id: 14},
  {name: "National Archives at New York", id: 15},
  {name: "National Archives at Philadelphia", id: 17},
	{name: "National Archives at Atlanta", id: 18},
	{name: "National Archives at Chicago", id: 19},
	{name: "National Archives at Kansas City", id: 20},
	{name: "National Archives at Fort Worth", id: 21},
	{name: "National Archives at Denver", id: 22},
	{name: "National Archives at Riverside", id: 23},
	{name: "National Archives at San Fransisco", id: 24},
	{name: "National Archives at Anchorage", id: 25},
	{name: "National Archives at Seattle", id: 26},
	{name: "National Personnel Records Center - Civilian Personnel Records", id: 27},
	{name: "National Personnel Records Center - Military Personnel Records", id: 28},
	{name: "National Archives - Washington, DC - Cartographic", id: 29},
	{name: "National Archives - Washington, DC - Motion Pictures", id: 30},
	{name: "National Archives - Washington, DC - Still Pictures", id: 31},
	{name: "National Archives - Washington, DC - Archives I Textual Reference", id: 32},
	{name: "National Archives - Washington, DC - Archives I Textual Reference (Civilian)", id: 33},
	{name: "National Archives - Washington, DC - FOIA", id: 34},
	{name: "National Archives - Washington, DC - Archives II Textual Reference (Military)", id: 35},
	{name: "Center for Legislative Archives", id: 36},
	{name: "National Archives - Washington, DC - Electronic", id: 37},
	{name: "Library of Congress, Prints and Photographs Division (an affiliated archives)", id: 38},
	{name: "National Park Service, Yellowstone National Park Archives (an affiliated archives)", id: 39},
	{name: "New Mexico Commission of Public Records, State Records Center, and Archives (an affiliated archives)", id: 40},
	{name: "Oklahoma Historical Society (an affiliated archives)", id: 41},
	{name: "Pennsylvania Historical and Museum Commission, State Archives (an affiliated archives)", id: 42},
	{name: "United States Military Academy Archives (an affiliated archives)", id: 43},
	{name: "United States Naval Academy, William W. Jeffries Memorial Archives (an affiliated archives)", id: 44},
	{name: "Presidential Materials Division", id: 48},
	{name: "National Archives at St. Louis", id: 50},
	{name: "Richard Nixon Library", id: 51},
	{name: "George W. Bush Library", id: 53},
	{name: "U.S. Government Printing Office (an affiliated archives)", id: 54},
	{name: "University of North Texas Libraries (an affiliated archives)", id: 57},	  
];
